import type { BudgetPlannerState } from "@/domain/budget/plannerTypes";

export const defaultBudgetState: BudgetPlannerState = {
  planningMonth: "2026-05",
  members: [
    { id: "primary", name: "Илья" },
    { id: "partner", name: "Супруга" },
  ],
  incomeSchedules: [
    {
      id: "primary-advance",
      memberId: "primary",
      title: "Аванс Ильи",
      kind: "advance",
      amount: 95_000,
      dayOfMonth: 25,
      time: "15:00",
      moveWeekendToFriday: true,
    },
    {
      id: "primary-salary",
      memberId: "primary",
      title: "Зарплата Ильи",
      kind: "salary",
      amount: 170_000,
      dayOfMonth: 10,
      time: "15:00",
      moveWeekendToFriday: true,
    },
    {
      id: "partner-advance",
      memberId: "partner",
      title: "Аванс супруги",
      kind: "advance",
      amount: 62_000,
      dayOfMonth: 25,
      time: "15:00",
      moveWeekendToFriday: true,
    },
    {
      id: "partner-salary",
      memberId: "partner",
      title: "Зарплата супруги",
      kind: "salary",
      amount: 93_000,
      dayOfMonth: 10,
      time: "15:00",
      moveWeekendToFriday: true,
    },
  ],
  incomeEvents: [],
  mandatoryPayments: [
    {
      id: "mortgage",
      memberId: "primary",
      title: "Ипотека",
      category: "Жилье",
      amount: 78_000,
      dueAt: "2026-05-15T10:00:00+03:00",
      scope: "personal",
    },
    {
      id: "partner-credit",
      memberId: "partner",
      title: "Кредит",
      category: "Личное",
      amount: 32_000,
      dueAt: "2026-05-12T09:00:00+03:00",
      scope: "personal",
    },
    {
      id: "utilities",
      title: "Коммуналка",
      category: "Дом",
      amount: 15_800,
      dueAt: "2026-05-17T09:00:00+03:00",
      scope: "shared",
    },
    {
      id: "subscriptions",
      title: "Подписки",
      category: "Сервисы",
      amount: 5_900,
      dueAt: "2026-05-20T12:00:00+03:00",
      scope: "shared",
    },
  ],
  funds: [
    {
      id: "groceries",
      title: "Продукты",
      monthlyLimit: 78_000,
      allocationWeight: 5,
      accent: "#111827",
      iconKey: "cart",
    },
    {
      id: "car",
      title: "Авто",
      monthlyLimit: 34_000,
      allocationWeight: 2,
      accent: "#2563eb",
      iconKey: "car",
    },
    {
      id: "leisure",
      title: "Выходные",
      monthlyLimit: 28_000,
      allocationWeight: 2,
      accent: "#c2410c",
      iconKey: "game",
    },
  ],
  goals: [
    {
      id: "renovation",
      title: "Большой ремонт",
      targetAmount: 1_400_000,
      currentAmount: 465_000,
      monthlyTarget: 120_000,
      deadline: "2026-12-20",
      accent: "#0f766e",
    },
    {
      id: "lighting",
      title: "Новое освещение",
      targetAmount: 240_000,
      currentAmount: 64_000,
      monthlyTarget: 38_000,
      deadline: "2026-08-15",
      accent: "#7c3aed",
    },
  ],
  transactions: [
    {
      id: "groceries-may-1",
      title: "Перекресток",
      amount: 12_400,
      occurredAt: "2026-05-06T18:30:00+03:00",
      kind: "fund",
      scope: "shared",
      categoryId: "groceries",
    },
    {
      id: "car-fuel-may",
      title: "Бензин",
      amount: 6_200,
      occurredAt: "2026-05-09T11:20:00+03:00",
      kind: "fund",
      scope: "shared",
      categoryId: "car",
    },
  ],
};
